fieldLayouts:
  deb42fd8-d371-4566-8fc9-296a2aa42626:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bdde76c8-4e6f-45f4-a8ef-69f856bc54c9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c2dc6cdf-4e8c-4a6c-b88d-0800be103a93 # Navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 971195b0-2353-4b17-b37b-8592d4aa8198
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 63b97843-edb4-4fe6-976b-12fdf98fd7b0
        userCondition: null
handle: header
hasTitleField: false
name: Header
section: b5276cbb-dff1-43ec-8bd6-5d4787b5f93b # Header
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
