baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en
name: 'Blitz Bug Eager Loading'
primary: true
siteGroup: 3b45e539-7b30-4421-9bfe-f319cd7f9794 # Blitz Bug Eager Loading
sortOrder: 1
