dateModified: 1700336769
email:
  fromEmail: andres@voan.ch
  fromName: 'Blitz Bug Eager Loading'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    3b45e539-7b30-4421-9bfe-f319cd7f9794: 'Blitz Bug Eager Loading' # Blitz Bug Eager Loading
    6a24e78f-0065-47b9-b06f-d48094e94c4b: Home # Home
    7e932b36-6494-4ab0-8508-9d85990c26da: Page # Page
    51025166-5ea9-48b7-8eff-d1ce65e22831: Common # Common
    91306678-9101-4cda-9d35-d3705845508d: Home # Home
    b5276cbb-dff1-43ec-8bd6-5d4787b5f93b: Header # Header
    c2dc6cdf-4e8c-4a6c-b88d-0800be103a93: Navigation # Navigation
    c9e7364d-d00e-4a7a-bb8d-92da1ccd7836: Header # Header
    e48e4796-7b9e-4211-aa16-ff37667f872f: Default # Default
    f77f2823-75d2-4434-bf3e-9b5cb6a46fc9: 'Blitz Bug Eager Loading' # Blitz Bug Eager Loading
plugins:
  blitz:
    edition: standard
    enabled: true
    licenseKey: UH9VBW33J6OD3BH5E7KQGPLY
    schemaVersion: 4.5.0
    settings:
      apiKey: ''
      cacheControlHeader: 'public, s-maxage=31536000, max-age=0'
      cacheControlHeaderExpired: 'public, s-maxage=5, max-age=0'
      cacheDuration: null
      cacheElementQueries: true
      cacheElements: true
      cacheGeneratorSettings:
        __assoc__:
          -
            - concurrency
            - '3'
      cacheGeneratorType: putyourlightson\blitz\drivers\generators\HttpGenerator
      cacheNonHtmlResponses: false
      cachePurgerType: putyourlightson\blitz\drivers\purgers\DummyPurger
      cacheStorageSettings:
        __assoc__:
          -
            - folderPath
            - '@webroot/cache/blitz'
          -
            - compressCachedValues
            - '1'
      cacheStorageType: putyourlightson\blitz\drivers\storage\FileStorage
      cachingEnabled: true
      debug: false
      defaultCacheControlHeader: 'no-cache, no-store, must-revalidate'
      deployerType: putyourlightson\blitz\drivers\deployers\DummyDeployer
      driverJobPriority: 100
      esiEnabled: false
      excludedQueryStringParams:
        -
          __assoc__:
            -
              - queryStringParam
              - gclid
        -
          __assoc__:
            -
              - queryStringParam
              - fbclid
      generatePagesWithQueryStringParams: true
      hintsEnabled: true
      includedQueryStringParams:
        -
          __assoc__:
            -
              - queryStringParam
              - '.*'
      includedUriPatterns:
        -
          __assoc__:
            -
              - uriPattern
              - '.*'
      injectScriptEvent: DOMContentLoaded
      integrations:
        - putyourlightson\blitz\drivers\integrations\CommerceIntegration
        - putyourlightson\blitz\drivers\integrations\FeedMeIntegration
        - putyourlightson\blitz\drivers\integrations\SeomaticIntegration
      maxRetryAttempts: 10
      maxUriLength: 255
      mutexTimeout: 1
      outputComments: true
      purgeAssetImagesWhenChanged: true
      queryStringCaching: 0
      queueJobTtr: 300
      refreshCacheAutomaticallyForGlobals: true
      refreshCacheJobPriority: 10
      refreshCacheWhenElementMovedInStructure: true
      refreshCacheWhenElementSavedNotLive: false
      refreshCacheWhenElementSavedUnchanged: false
      refreshMode: 3
      sendPoweredByHeader: true
      ssiEnabled: false
      trackElementQueries: true
      trackElements: true
system:
  edition: solo
  live: true
  name: 'Blitz Bug Eager Loading'
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
