defaultPlacement: end
enableVersioning: true
handle: header
name: Header
propagationMethod: all
siteSettings:
  f77f2823-75d2-4434-bf3e-9b5cb6a46fc9: # Blitz Bug Eager Loading
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
