defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  f77f2823-75d2-4434-bf3e-9b5cb6a46fc9: # Blitz Bug Eager Loading
    enabledByDefault: true
    hasUrls: true
    template: home/_entry
    uriFormat: __home__
type: single
